// © 2026 Platform Engineering Labs Inc.
//
// SPDX-License-Identifier: FSL-1.1-ALv2

//go:build e2e

package e2e_test

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"
)

// The formae that put a real cloud plugin behind federated credentials.
//
// They cannot be static fixtures: the trust coordinate each target names —
// the role ARN on AWS, the workload identity provider on GCP — is provisioned
// per run by `formae connect` and does not exist until it has run. So they are
// rendered from the coordinate the run reported.
//
// They are written into the fixtures directory rather than a temp one because
// that is where the generated PklProject lives, and `@formae` / `@aws` / `@gcp`
// resolve through it. A per-run filename keeps two runs from colliding, and
// cleanup removes the file.

// The labels and names the generated formae use. The stack and target labels
// are shared between clouds because only one of the two formae is ever applied
// against a given agent; the resource names carry the suite's own prefix so
// the aws-nuke allowlist and the pre-cleanup purge can reclaim anything a dead
// run leaves behind, and a per-run suffix so two runs cannot collide.
const (
	oidcRealStackLabel       = "e2e-oidc-real"
	oidcRealTargetLabel      = "e2e-oidc-real-target"
	oidcRealAWSResourceLabel = "e2e-oidc-real-igw"
	oidcRealGCPResourceLabel = "e2e-oidc-real-sa"

	// awsRegion is where the federated target operates. The trust is global —
	// IAM and STS both are — but a target must name a region.
	awsRegion = "us-west-2"
)

// oidcRealAWSResourceName is the Name tag the internet gateway carries, which
// is how the test finds it and how aws-nuke is allowed to reclaim it.
func oidcRealAWSResourceName() string { return "formae-e2e-oidc-igw-" + ConnectRunSuffix() }

// oidcRealGCPAccountID is the service account id. GCP requires 6-30
// characters, lowercase alphanumeric or hyphen, starting with a letter.
func oidcRealGCPAccountID() string { return "formae-e2e-oidc-" + ConnectRunSuffix() }

// oidcRealAWSForma declares one target authenticating by federated identity
// and one resource for it to manage. An internet gateway is chosen for being
// the cheapest thing in the account that is unambiguously real: it has no
// dependencies, costs nothing while it exists, and either exists or does not.
const oidcRealAWSForma = `/*
 * © 2026 Platform Engineering Labs Inc.
 *
 * SPDX-License-Identifier: FSL-1.1-ALv2
 */

/// Generated by the oidc-credential e2e. The role ARN is provisioned per run
/// by ` + "`formae connect aws`" + `, so this file is rendered, not stored.
amends "@formae/forma.pkl"

import "@formae/formae.pkl"
import "@aws/aws.pkl"
import "@aws/ec2/internetgateway.pkl"

/// The target's credentials come from the paired oidc-credential broker: the
/// plugin mints an identity token for sts.amazonaws.com and assumes this role
/// with it. Nothing here names an access key, a profile or an environment.
local oidcTarget = new formae.Target {
  label = %q
  config = new aws.Config {
    region = %q
    auth = new aws.OidcAuth {
      roleArn = %q
    }
  }
}

forma {
  new formae.Stack {
    label = %q
    description = "E2E test: a real AWS plugin managing a resource under federated credentials"
  }

  oidcTarget

  new internetgateway.InternetGateway {
    label = %q
    target = oidcTarget.res
    tags {
      new {
        key = "Name"
        value = %q
      }
    }
  }
}
`

// oidcRealGCPForma is the GCP counterpart. A service account is the analogue
// of the internet gateway: real, free, and creatable in a project with no
// billing account, which this one deliberately has none of.
const oidcRealGCPForma = `/*
 * © 2026 Platform Engineering Labs Inc.
 *
 * SPDX-License-Identifier: FSL-1.1-ALv2
 */

/// Generated by the oidc-credential e2e. The workload identity provider is
/// provisioned per run by ` + "`formae connect gcp`" + `, so this file is
/// rendered, not stored.
amends "@formae/forma.pkl"

import "@formae/formae.pkl"
import "@gcp/gcp.pkl"
import "@gcp/iam/serviceAccount.pkl"

/// The provider resource name is both the trust coordinate and the audience
/// of every token minted for this target.
local oidcTarget = new formae.Target {
  label = %q
  config = new gcp.Config {
    project = %q
    auth = new gcp.OidcAuth {
      workloadIdentityProvider = %q
    }
  }
}

forma {
  new formae.Stack {
    label = %q
    description = "E2E test: a real GCP plugin managing a resource under federated credentials"
  }

  oidcTarget

  new serviceAccount.ServiceAccount {
    label = %q
    // The schema calls it name, but it is the accountId: 6-30 characters,
    // lowercase alphanumeric or hyphen, starting with a letter. The API
    // derives the email and the full resource path from it.
    name = %q
    target = oidcTarget.res
    displayName = "formae oidc-credential e2e"
  }
}
`

// WriteGeneratedForma renders content into the fixtures directory under a
// per-run name and removes it afterwards, returning the path to apply.
func WriteGeneratedForma(t *testing.T, name, content string) string {
	t.Helper()

	path := filepath.Join(fixturesDir(t), name)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("failed to write the generated forma %s: %v", path, err)
	}
	t.Cleanup(func() {
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			t.Errorf("cleanup: removing the generated forma %s: %v", path, err)
		}
	})
	return path
}

// oidcRealAWSFormaFor renders the AWS forma for this run.
func oidcRealAWSFormaFor(t *testing.T, roleARN string) string {
	t.Helper()

	content := fmt.Sprintf(oidcRealAWSForma,
		oidcRealTargetLabel, awsRegion, roleARN,
		oidcRealStackLabel, oidcRealAWSResourceLabel, oidcRealAWSResourceName())
	return WriteGeneratedForma(t, "oidc_real_aws_"+ConnectRunSuffix()+".pkl", content)
}

// oidcRealGCPFormaFor renders the GCP forma for this run.
func oidcRealGCPFormaFor(t *testing.T, project, provider string) string {
	t.Helper()

	content := fmt.Sprintf(oidcRealGCPForma,
		oidcRealTargetLabel, project, provider,
		oidcRealStackLabel, oidcRealGCPResourceLabel, oidcRealGCPAccountID())
	return WriteGeneratedForma(t, "oidc_real_gcp_"+ConnectRunSuffix()+".pkl", content)
}
