version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    # - gocyclo
    - unused
    - misspell
    # - godox # catch TODO/FIXME comments
  settings:
    staticcheck:
      checks:
        - "all"
        - "-ST1005"     # don't enforce error string capitalization
        - "-ST1000"     # don't enforce package comments
        - "-SA1029"     # don't enforce string literal rules
        - "-QF1003"     # don't enforce if/else to switch statements
        - "-ST1003"     # don't enforce capitalized acronyms
        - "-ST1021"
        - "-ST1020"
    gocyclo:
      min-complexity: 35

formatters:
  enable:
    - gofmt
    - goimports
