version = 1

# Configuration files
[[annotations]]
path = ["docs/docs.go", "**/*.yml", "**/*.yaml", "**/*.json", "**/*.mod", "**/*.sum", "**/*.lock", "**/*.toml", ".gitignore", "**/.gitignore", "Makefile", "**/PklProject"]
SPDX-FileCopyrightText = "© 2025 Platform Engineering Labs Inc."
SPDX-License-Identifier = "FSL-1.1-ALv2"

# Shell scripts in scripts/ directory
[[annotations]]
path = ["scripts/*.sh"]
SPDX-FileCopyrightText = "© 2025 Platform Engineering Labs Inc."
SPDX-License-Identifier = "FSL-1.1-ALv2"

# Documentation files
[[annotations]]
path = ["**/*.md", "**/*.html"]
SPDX-FileCopyrightText = "© 2025 Platform Engineering Labs Inc."
SPDX-License-Identifier = "FSL-1.1-ALv2"

# Binary and generated test files
[[annotations]]
path = ["**/*.zip", "**/*.pcf", "**/*.log"]
SPDX-FileCopyrightText = "© 2025 Platform Engineering Labs Inc."
SPDX-License-Identifier = "FSL-1.1-ALv2"

# Dockerfile
[[annotations]]
path = ["**/Dockerfile*"]
SPDX-FileCopyrightText = "© 2025 Platform Engineering Labs Inc."
SPDX-License-Identifier = "FSL-1.1-ALv2"

# Third-party files from Pkl project (Apache-2.0)
[[annotations]]
path = ["plugins/pkl/schema/ext/URI.pkl"]
SPDX-FileCopyrightText = "Copyright © 2024 Apple Inc. and the Pkl project authors. All rights reserved."
SPDX-License-Identifier = "Apache-2.0"
