-- © 2026 Platform Engineering Labs Inc.
-- SPDX-License-Identifier: FSL-1.1-ALv2
-- +goose Up
-- Resource predicate scopes are advanced under the existing URI serialization,
-- before the common sorted revision-lock pass. Full URI history participates.
-- Target identities use physical target equality, also conservatively covering
-- embedded Target values used by in-memory maps. SQL Server MAX retains long
-- JSON targets; registration uses a locked insert recheck, never truncation.
-- Resource identity uses the physical ksuid column, which loaders restore over JSON.
CREATE TABLE admission_inventory_targets (label TEXT NOT NULL PRIMARY KEY, guard_key TEXT COLLATE BINARY NOT NULL UNIQUE DEFAULT ('admission:inventory-target:' || lower(hex(randomblob(16)))));
CREATE TABLE admission_resource_ids (label TEXT NOT NULL PRIMARY KEY, guard_key TEXT COLLATE BINARY NOT NULL UNIQUE DEFAULT ('admission:resource-id:' || lower(hex(randomblob(16)))));
DROP TRIGGER admission_resources_insert;
DROP TRIGGER admission_resources_update;
DROP TRIGGER admission_resources_delete;
-- +goose StatementBegin
CREATE TRIGGER admission_resources_insert BEFORE INSERT ON resources BEGIN
INSERT INTO admission_resource_uris(uri) SELECT DISTINCT uri FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) affected WHERE 1=1 ON CONFLICT(uri) DO NOTHING;
INSERT INTO admission_revisions(guard_key,revision) SELECT u.guard_key,1 FROM admission_resource_uris u JOIN (SELECT DISTINCT uri FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) affected) a ON a.uri=u.uri WHERE 1=1 ORDER BY u.guard_key ON CONFLICT(guard_key) DO UPDATE SET revision=revision+1;
INSERT INTO admission_inventory_targets(label) SELECT DISTINCT label FROM (SELECT r.target AS label FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Target') FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r UNION SELECT h.target FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Target') FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r ON h.uri=r.uri) scopes WHERE label IS NOT NULL ON CONFLICT(label) DO NOTHING;
INSERT INTO admission_resource_ids(label) SELECT DISTINCT label FROM (SELECT r.ksuid AS label FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r UNION SELECT h.ksuid FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r ON h.uri=r.uri) scopes WHERE label IS NOT NULL ON CONFLICT(label) DO NOTHING;
INSERT INTO admission_stack_labels(label) SELECT DISTINCT label FROM (SELECT r.stack AS label FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Stack') FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r UNION SELECT h.stack FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Stack') FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r ON h.uri=r.uri) labels WHERE label IS NOT NULL ON CONFLICT(label) DO NOTHING;
INSERT INTO admission_revisions(guard_key,revision) SELECT guard_key,1 FROM (SELECT l.guard_key FROM admission_stack_labels l JOIN (SELECT r.stack AS label FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Stack') FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r UNION SELECT h.stack FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Stack') FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r ON h.uri=r.uri) x ON l.label=x.label
UNION
SELECT p.guard_key FROM admission_inventory_targets p JOIN (SELECT r.target AS label FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Target') FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r UNION SELECT h.target FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Target') FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r ON h.uri=r.uri) x ON p.label=x.label
UNION
SELECT p.guard_key FROM admission_resource_ids p JOIN (SELECT r.ksuid AS label FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r UNION SELECT h.ksuid FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r ON h.uri=r.uri) x ON p.label=x.label
UNION
SELECT CASE WHEN length(RTRIM(s.id)) BETWEEN 1 AND 128 AND RTRIM(s.id) NOT GLOB '*[^A-Za-z0-9_-]*' THEN 'admission:stack:' || RTRIM(s.id) ELSE 'admission:stack:exceptional' END AS guard_key FROM stacks s JOIN (SELECT r.stack AS label FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Stack') FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r UNION SELECT h.stack FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Stack') FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r ON h.uri=r.uri) x ON s.label=x.label
UNION
SELECT 'admission:topology' AS guard_key WHERE EXISTS (SELECT 1 FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.target, previous.ksuid, previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r WHERE (CAST(r.data AS TEXT) LIKE '%$ref%' OR CAST(r.data AS TEXT) LIKE '%$gen%' OR CAST(r.data AS TEXT) LIKE '%' || char(92) || '%') OR EXISTS (SELECT 1 FROM resources h WHERE h.uri=r.uri AND ((CAST(h.data AS TEXT) LIKE '%$ref%' OR CAST(h.data AS TEXT) LIKE '%$gen%' OR CAST(h.data AS TEXT) LIKE '%' || char(92) || '%'))))) keys WHERE 1=1 ORDER BY guard_key ON CONFLICT(guard_key) DO UPDATE SET revision=revision+1;
END;
-- +goose StatementEnd
-- +goose StatementBegin
CREATE TRIGGER admission_resources_update BEFORE UPDATE ON resources BEGIN
INSERT INTO admission_resource_uris(uri) SELECT DISTINCT uri FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) affected WHERE 1=1 ON CONFLICT(uri) DO NOTHING;
INSERT INTO admission_revisions(guard_key,revision) SELECT u.guard_key,1 FROM admission_resource_uris u JOIN (SELECT DISTINCT uri FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) affected) a ON a.uri=u.uri WHERE 1=1 ORDER BY u.guard_key ON CONFLICT(guard_key) DO UPDATE SET revision=revision+1;
INSERT INTO admission_inventory_targets(label) SELECT DISTINCT label FROM (SELECT r.target AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Target') FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r UNION SELECT h.target FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Target') FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r ON h.uri=r.uri) scopes WHERE label IS NOT NULL ON CONFLICT(label) DO NOTHING;
INSERT INTO admission_resource_ids(label) SELECT DISTINCT label FROM (SELECT r.ksuid AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r UNION SELECT h.ksuid FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r ON h.uri=r.uri) scopes WHERE label IS NOT NULL ON CONFLICT(label) DO NOTHING;
INSERT INTO admission_stack_labels(label) SELECT DISTINCT label FROM (SELECT r.stack AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Stack') FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Stack') FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r ON h.uri=r.uri) labels WHERE label IS NOT NULL ON CONFLICT(label) DO NOTHING;
INSERT INTO admission_revisions(guard_key,revision) SELECT guard_key,1 FROM (SELECT l.guard_key FROM admission_stack_labels l JOIN (SELECT r.stack AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Stack') FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Stack') FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r ON h.uri=r.uri) x ON l.label=x.label
UNION
SELECT p.guard_key FROM admission_inventory_targets p JOIN (SELECT r.target AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Target') FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r UNION SELECT h.target FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Target') FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r ON h.uri=r.uri) x ON p.label=x.label
UNION
SELECT p.guard_key FROM admission_resource_ids p JOIN (SELECT r.ksuid AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r UNION SELECT h.ksuid FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r ON h.uri=r.uri) x ON p.label=x.label
UNION
SELECT CASE WHEN length(RTRIM(s.id)) BETWEEN 1 AND 128 AND RTRIM(s.id) NOT GLOB '*[^A-Za-z0-9_-]*' THEN 'admission:stack:' || RTRIM(s.id) ELSE 'admission:stack:exceptional' END AS guard_key FROM stacks s JOIN (SELECT r.stack AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Stack') FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Stack') FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r ON h.uri=r.uri) x ON s.label=x.label
UNION
SELECT 'admission:topology' AS guard_key WHERE EXISTS (SELECT 1 FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r WHERE (CAST(r.data AS TEXT) LIKE '%$ref%' OR CAST(r.data AS TEXT) LIKE '%$gen%' OR CAST(r.data AS TEXT) LIKE '%' || char(92) || '%') OR EXISTS (SELECT 1 FROM resources h WHERE h.uri=r.uri AND ((CAST(h.data AS TEXT) LIKE '%$ref%' OR CAST(h.data AS TEXT) LIKE '%$gen%' OR CAST(h.data AS TEXT) LIKE '%' || char(92) || '%'))))) keys WHERE 1=1 ORDER BY guard_key ON CONFLICT(guard_key) DO UPDATE SET revision=revision+1;
END;
-- +goose StatementEnd
-- +goose StatementBegin
CREATE TRIGGER admission_resources_delete BEFORE DELETE ON resources BEGIN
INSERT INTO admission_resource_uris(uri) SELECT DISTINCT uri FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) affected WHERE 1=1 ON CONFLICT(uri) DO NOTHING;
INSERT INTO admission_revisions(guard_key,revision) SELECT u.guard_key,1 FROM admission_resource_uris u JOIN (SELECT DISTINCT uri FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) affected) a ON a.uri=u.uri WHERE 1=1 ORDER BY u.guard_key ON CONFLICT(guard_key) DO UPDATE SET revision=revision+1;
INSERT INTO admission_inventory_targets(label) SELECT DISTINCT label FROM (SELECT r.target AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Target') FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r UNION SELECT h.target FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Target') FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r ON h.uri=r.uri) scopes WHERE label IS NOT NULL ON CONFLICT(label) DO NOTHING;
INSERT INTO admission_resource_ids(label) SELECT DISTINCT label FROM (SELECT r.ksuid AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r UNION SELECT h.ksuid FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r ON h.uri=r.uri) scopes WHERE label IS NOT NULL ON CONFLICT(label) DO NOTHING;
INSERT INTO admission_stack_labels(label) SELECT DISTINCT label FROM (SELECT r.stack AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Stack') FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Stack') FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r ON h.uri=r.uri) labels WHERE label IS NOT NULL ON CONFLICT(label) DO NOTHING;
INSERT INTO admission_revisions(guard_key,revision) SELECT guard_key,1 FROM (SELECT l.guard_key FROM admission_stack_labels l JOIN (SELECT r.stack AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Stack') FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Stack') FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r ON h.uri=r.uri) x ON l.label=x.label
UNION
SELECT p.guard_key FROM admission_inventory_targets p JOIN (SELECT r.target AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Target') FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r UNION SELECT h.target FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Target') FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r ON h.uri=r.uri) x ON p.label=x.label
UNION
SELECT p.guard_key FROM admission_resource_ids p JOIN (SELECT r.ksuid AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r UNION SELECT h.ksuid FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r ON h.uri=r.uri) x ON p.label=x.label
UNION
SELECT CASE WHEN length(RTRIM(s.id)) BETWEEN 1 AND 128 AND RTRIM(s.id) NOT GLOB '*[^A-Za-z0-9_-]*' THEN 'admission:stack:' || RTRIM(s.id) ELSE 'admission:stack:exceptional' END AS guard_key FROM stacks s JOIN (SELECT r.stack AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Stack') FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Stack') FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r ON h.uri=r.uri) x ON s.label=x.label
UNION
SELECT 'admission:topology' AS guard_key WHERE EXISTS (SELECT 1 FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r WHERE (CAST(r.data AS TEXT) LIKE '%$ref%' OR CAST(r.data AS TEXT) LIKE '%$gen%' OR CAST(r.data AS TEXT) LIKE '%' || char(92) || '%') OR EXISTS (SELECT 1 FROM resources h WHERE h.uri=r.uri AND ((CAST(h.data AS TEXT) LIKE '%$ref%' OR CAST(h.data AS TEXT) LIKE '%$gen%' OR CAST(h.data AS TEXT) LIKE '%' || char(92) || '%'))))) keys WHERE 1=1 ORDER BY guard_key ON CONFLICT(guard_key) DO UPDATE SET revision=revision+1;
END;
-- +goose StatementEnd
-- +goose Down
DROP TRIGGER admission_resources_insert;
DROP TRIGGER admission_resources_update;
DROP TRIGGER admission_resources_delete;
-- +goose StatementBegin
CREATE TRIGGER admission_resources_insert BEFORE INSERT ON resources BEGIN
INSERT INTO admission_resource_uris(uri) SELECT DISTINCT uri FROM (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) affected WHERE 1=1 ON CONFLICT(uri) DO NOTHING;
INSERT INTO admission_revisions(guard_key,revision) SELECT u.guard_key,1 FROM admission_resource_uris u JOIN (SELECT DISTINCT uri FROM (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) affected) a ON a.uri=u.uri WHERE 1=1 ORDER BY u.guard_key ON CONFLICT(guard_key) DO UPDATE SET revision=revision+1;
INSERT INTO admission_stack_labels(label) SELECT DISTINCT label FROM (SELECT r.stack AS label FROM (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Stack') FROM (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r UNION SELECT h.stack FROM resources h JOIN (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Stack') FROM resources h JOIN (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r ON h.uri=r.uri) labels WHERE label IS NOT NULL ON CONFLICT(label) DO NOTHING;
INSERT INTO admission_revisions(guard_key,revision) SELECT guard_key,1 FROM (SELECT l.guard_key FROM admission_stack_labels l JOIN (SELECT r.stack AS label FROM (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Stack') FROM (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r UNION SELECT h.stack FROM resources h JOIN (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Stack') FROM resources h JOIN (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r ON h.uri=r.uri) x ON l.label=x.label
UNION
SELECT CASE WHEN length(RTRIM(s.id)) BETWEEN 1 AND 128 AND RTRIM(s.id) NOT GLOB '*[^A-Za-z0-9_-]*' THEN 'admission:stack:' || RTRIM(s.id) ELSE 'admission:stack:exceptional' END AS guard_key FROM stacks s JOIN (SELECT r.stack AS label FROM (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Stack') FROM (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r UNION SELECT h.stack FROM resources h JOIN (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Stack') FROM resources h JOIN (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r ON h.uri=r.uri) x ON s.label=x.label
UNION
SELECT 'admission:topology' AS guard_key WHERE EXISTS (SELECT 1 FROM (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri UNION ALL SELECT previous.stack, previous.data, previous.uri FROM resources previous WHERE previous.uri=NEW.uri AND previous.version=NEW.version) r WHERE (CAST(r.data AS TEXT) LIKE '%$ref%' OR CAST(r.data AS TEXT) LIKE '%$gen%' OR CAST(r.data AS TEXT) LIKE '%' || char(92) || '%') OR EXISTS (SELECT 1 FROM resources h WHERE h.uri=r.uri AND ((CAST(h.data AS TEXT) LIKE '%$ref%' OR CAST(h.data AS TEXT) LIKE '%$gen%' OR CAST(h.data AS TEXT) LIKE '%' || char(92) || '%'))))) keys WHERE 1=1 ORDER BY guard_key ON CONFLICT(guard_key) DO UPDATE SET revision=revision+1;
END;
-- +goose StatementEnd
-- +goose StatementBegin
CREATE TRIGGER admission_resources_update BEFORE UPDATE ON resources BEGIN
INSERT INTO admission_resource_uris(uri) SELECT DISTINCT uri FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) affected WHERE 1=1 ON CONFLICT(uri) DO NOTHING;
INSERT INTO admission_revisions(guard_key,revision) SELECT u.guard_key,1 FROM admission_resource_uris u JOIN (SELECT DISTINCT uri FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) affected) a ON a.uri=u.uri WHERE 1=1 ORDER BY u.guard_key ON CONFLICT(guard_key) DO UPDATE SET revision=revision+1;
INSERT INTO admission_stack_labels(label) SELECT DISTINCT label FROM (SELECT r.stack AS label FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Stack') FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Stack') FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r ON h.uri=r.uri) labels WHERE label IS NOT NULL ON CONFLICT(label) DO NOTHING;
INSERT INTO admission_revisions(guard_key,revision) SELECT guard_key,1 FROM (SELECT l.guard_key FROM admission_stack_labels l JOIN (SELECT r.stack AS label FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Stack') FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Stack') FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r ON h.uri=r.uri) x ON l.label=x.label
UNION
SELECT CASE WHEN length(RTRIM(s.id)) BETWEEN 1 AND 128 AND RTRIM(s.id) NOT GLOB '*[^A-Za-z0-9_-]*' THEN 'admission:stack:' || RTRIM(s.id) ELSE 'admission:stack:exceptional' END AS guard_key FROM stacks s JOIN (SELECT r.stack AS label FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Stack') FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Stack') FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r ON h.uri=r.uri) x ON s.label=x.label
UNION
SELECT 'admission:topology' AS guard_key WHERE EXISTS (SELECT 1 FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri) r WHERE (CAST(r.data AS TEXT) LIKE '%$ref%' OR CAST(r.data AS TEXT) LIKE '%$gen%' OR CAST(r.data AS TEXT) LIKE '%' || char(92) || '%') OR EXISTS (SELECT 1 FROM resources h WHERE h.uri=r.uri AND ((CAST(h.data AS TEXT) LIKE '%$ref%' OR CAST(h.data AS TEXT) LIKE '%$gen%' OR CAST(h.data AS TEXT) LIKE '%' || char(92) || '%'))))) keys WHERE 1=1 ORDER BY guard_key ON CONFLICT(guard_key) DO UPDATE SET revision=revision+1;
END;
-- +goose StatementEnd
-- +goose StatementBegin
CREATE TRIGGER admission_resources_delete BEFORE DELETE ON resources BEGIN
INSERT INTO admission_resource_uris(uri) SELECT DISTINCT uri FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) affected WHERE 1=1 ON CONFLICT(uri) DO NOTHING;
INSERT INTO admission_revisions(guard_key,revision) SELECT u.guard_key,1 FROM admission_resource_uris u JOIN (SELECT DISTINCT uri FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) affected) a ON a.uri=u.uri WHERE 1=1 ORDER BY u.guard_key ON CONFLICT(guard_key) DO UPDATE SET revision=revision+1;
INSERT INTO admission_stack_labels(label) SELECT DISTINCT label FROM (SELECT r.stack AS label FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Stack') FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Stack') FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r ON h.uri=r.uri) labels WHERE label IS NOT NULL ON CONFLICT(label) DO NOTHING;
INSERT INTO admission_revisions(guard_key,revision) SELECT guard_key,1 FROM (SELECT l.guard_key FROM admission_stack_labels l JOIN (SELECT r.stack AS label FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Stack') FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Stack') FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r ON h.uri=r.uri) x ON l.label=x.label
UNION
SELECT CASE WHEN length(RTRIM(s.id)) BETWEEN 1 AND 128 AND RTRIM(s.id) NOT GLOB '*[^A-Za-z0-9_-]*' THEN 'admission:stack:' || RTRIM(s.id) ELSE 'admission:stack:exceptional' END AS guard_key FROM stacks s JOIN (SELECT r.stack AS label FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r UNION SELECT json_extract(CASE WHEN json_valid(r.data) THEN r.data ELSE '{}' END, '$.Stack') FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r ON h.uri=r.uri UNION SELECT json_extract(CASE WHEN json_valid(h.data) THEN h.data ELSE '{}' END, '$.Stack') FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r ON h.uri=r.uri) x ON s.label=x.label
UNION
SELECT 'admission:topology' AS guard_key WHERE EXISTS (SELECT 1 FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri) r WHERE (CAST(r.data AS TEXT) LIKE '%$ref%' OR CAST(r.data AS TEXT) LIKE '%$gen%' OR CAST(r.data AS TEXT) LIKE '%' || char(92) || '%') OR EXISTS (SELECT 1 FROM resources h WHERE h.uri=r.uri AND ((CAST(h.data AS TEXT) LIKE '%$ref%' OR CAST(h.data AS TEXT) LIKE '%$gen%' OR CAST(h.data AS TEXT) LIKE '%' || char(92) || '%'))))) keys WHERE 1=1 ORDER BY guard_key ON CONFLICT(guard_key) DO UPDATE SET revision=revision+1;
END;
-- +goose StatementEnd
DROP TABLE admission_resource_ids;
DROP TABLE admission_inventory_targets;
