// © 2025 Platform Engineering Labs Inc.
//
// SPDX-License-Identifier: FSL-1.1-ALv2

package pkl

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/masterminds/semver"
)

const autoGeneratedHeader = "/// Auto-generated wrapper for "

// GeneratePluginWrappers scans pluginDirs for installed plugins that contain
// schema/Config.pkl and writes a PascalCase wrapper PKL file in wrapperDir
// for each one. Multiple plugin dirs are merged with first-wins semantics
// (mirroring discovery.DiscoverPluginsMulti), so a dev plugin under
// wrapperDir overrides a system-installed plugin of the same name.
//
// Wrappers for plugins that live directly under wrapperDir use a relative
// path so they resolve through the plugins:/ FS scheme; plugins discovered
// in any other directory (e.g. SystemPluginDir) get an absolute file:// URI.
//
// After writing, any wrapper carrying the auto-generated header whose plugin
// is no longer present in the merged scan is removed. Hand-written .pkl
// files in wrapperDir are left untouched.
//
// Resulting wrappers allow users to write:
//
//	import "plugins:/AuthBasic.pkl" as AuthBasic
//	new AuthBasic.AgentConfig { ... }
func GeneratePluginWrappers(wrapperDir string, pluginDirs []string) error {
	if wrapperDir == "" {
		return nil
	}

	seen := make(map[string]bool)
	expected := make(map[string]bool)

	for _, dir := range pluginDirs {
		if dir == "" {
			continue
		}
		entries, err := os.ReadDir(dir)
		if err != nil {
			continue
		}
		for _, entry := range entries {
			pluginName := entry.Name()
			if seen[pluginName] {
				continue
			}
			pluginPath := filepath.Join(dir, pluginName)
			if !isDirFollowingSymlinks(pluginPath) {
				continue
			}

			versionDir := findHighestVersionDir(pluginPath)
			if versionDir == "" {
				continue
			}
			configPath := filepath.Join(pluginPath, versionDir, "schema", "Config.pkl")
			if _, err := os.Stat(configPath); err != nil {
				continue
			}
			seen[pluginName] = true

			wrapperName := toPascalCase(pluginName) + ".pkl"
			wrapperPath := filepath.Join(wrapperDir, wrapperName)

			extendsURI := wrapperExtendsURI(wrapperDir, dir, pluginName, versionDir)
			content := fmt.Sprintf(
				"%s%s plugin.\n"+
					"/// Do not edit; regenerated on each config evaluation.\n"+
					"extends \"%s\"\n",
				autoGeneratedHeader, pluginName, extendsURI,
			)
			if err := os.WriteFile(wrapperPath, []byte(content), 0644); err != nil {
				return fmt.Errorf("writing wrapper %s: %w", wrapperPath, err)
			}
			expected[wrapperName] = true
		}
	}

	if err := sweepStaleWrappers(wrapperDir, expected); err != nil {
		return err
	}
	return nil
}

// wrapperExtendsURI returns the URI to put in the wrapper's `extends` clause.
// Plugins under wrapperDir use a relative path (resolved via the plugins:/
// FS scheme); plugins elsewhere use an absolute file:// URI.
func wrapperExtendsURI(wrapperDir, pluginDir, pluginName, versionDir string) string {
	wrapperAbs, errW := filepath.Abs(wrapperDir)
	pluginAbs, errP := filepath.Abs(pluginDir)
	if errW == nil && errP == nil && wrapperAbs == pluginAbs {
		return fmt.Sprintf("./%s/%s/schema/Config.pkl", pluginName, versionDir)
	}
	if errP != nil {
		pluginAbs = pluginDir
	}
	return "file://" + filepath.Join(pluginAbs, pluginName, versionDir, "schema", "Config.pkl")
}

// sweepStaleWrappers removes auto-generated wrappers in wrapperDir whose
// filename is not in `expected`. Files without the auto-generated header
// (i.e. hand-written) are never touched.
func sweepStaleWrappers(wrapperDir string, expected map[string]bool) error {
	entries, err := os.ReadDir(wrapperDir)
	if err != nil {
		return nil
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if !strings.HasSuffix(name, ".pkl") {
			continue
		}
		if expected[name] {
			continue
		}
		path := filepath.Join(wrapperDir, name)
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		if !strings.HasPrefix(string(data), autoGeneratedHeader) {
			continue
		}
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("removing stale wrapper %s: %w", path, err)
		}
	}
	return nil
}

// isDirFollowingSymlinks reports whether path is a directory, following
// symlinks. os.DirEntry.IsDir() returns false for a symlink even when the
// target is a directory, which would skip plugins installed via symlink
// (common in dev setups).
func isDirFollowingSymlinks(path string) bool {
	info, err := os.Stat(path)
	if err != nil {
		return false
	}
	return info.IsDir()
}

// findHighestVersionDir returns the name of the highest semver directory inside
// dir (e.g. "v0.2.0"). Returns "" if no version directories are found.
func findHighestVersionDir(dir string) string {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return ""
	}

	var versions []string
	for _, entry := range entries {
		if !isDirFollowingSymlinks(filepath.Join(dir, entry.Name())) {
			continue
		}
		name := entry.Name()
		if strings.HasPrefix(name, "v") {
			versions = append(versions, name)
		}
	}

	if len(versions) == 0 {
		return ""
	}

	sort.Slice(versions, func(i, j int) bool {
		vi, errI := semver.NewVersion(versions[i])
		vj, errJ := semver.NewVersion(versions[j])
		if errI != nil || errJ != nil {
			return versions[i] > versions[j]
		}
		return vi.GreaterThan(vj)
	})

	return versions[0]
}

// toPascalCase converts a hyphenated plugin name to PascalCase.
// For example: "auth-basic" -> "AuthBasic", "gcp" -> "Gcp".
func toPascalCase(s string) string {
	parts := strings.Split(s, "-")
	var b strings.Builder
	for _, part := range parts {
		if len(part) == 0 {
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		if len(part) > 1 {
			b.WriteString(part[1:])
		}
	}
	return b.String()
}

// defaultPluginDir returns the plugin directory path. It checks the
// FORMAE_PLUGIN_DIR environment variable first, falling back to
// ~/.pel/formae/plugins. This allows custom plugin directories to be
// resolved at config-evaluation time (before the config's own pluginDir
// field is available).
func defaultPluginDir() string {
	if dir := os.Getenv("FORMAE_PLUGIN_DIR"); dir != "" {
		return dir
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return filepath.Join(home, ".pel", "formae", "plugins")
}
