// © 2025 Platform Engineering Labs Inc.
//
// SPDX-License-Identifier: FSL-1.1-ALv2

//go:build unit

package pkl

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func writeFakePlugin(t *testing.T, root, name, version string) {
	t.Helper()
	configDir := filepath.Join(root, name, version, "schema")
	require.NoError(t, os.MkdirAll(configDir, 0755))
	require.NoError(t, os.WriteFile(
		filepath.Join(configDir, "Config.pkl"),
		[]byte("open module "+name+".Config\n"),
		0644,
	))
}

// fakeExeForSystemDir fabricates an executable path such that
// discovery.SystemPluginDir(exe) returns systemDir, by following the inverse
// of installRoot/bin/<name> -> installRoot/formae/plugins. The returned path
// does not need to exist on disk.
func fakeExeForSystemDir(t *testing.T, systemDir string) string {
	t.Helper()
	installRoot := filepath.Dir(filepath.Dir(systemDir))
	return filepath.Join(installRoot, "bin", "formae")
}

func TestGeneratePluginWrappers_CreatesWrapperForPluginWithSchema(t *testing.T) {
	pluginDir := t.TempDir()
	writeFakePlugin(t, pluginDir, "auth-basic", "v0.1.0")

	require.NoError(t, GeneratePluginWrappers(pluginDir))

	wrapperPath := filepath.Join(pluginDir, "AuthBasic.pkl")
	content, err := os.ReadFile(wrapperPath)
	require.NoError(t, err)

	assert.Contains(t, string(content), `extends "./auth-basic/v0.1.0/schema/Config.pkl"`)
	assert.Contains(t, string(content), "Auto-generated wrapper for auth-basic plugin")
}

func TestGeneratePluginWrappers_SkipsPluginsWithoutSchema(t *testing.T) {
	pluginDir := t.TempDir()

	require.NoError(t, os.MkdirAll(filepath.Join(pluginDir, "aws", "v0.1.3", "schema"), 0755))

	require.NoError(t, GeneratePluginWrappers(pluginDir))

	_, err := os.Stat(filepath.Join(pluginDir, "Aws.pkl"))
	assert.True(t, os.IsNotExist(err), "expected no wrapper for plugin without Config.pkl")
}

func TestGeneratePluginWrappers_EmptyDir(t *testing.T) {
	pluginDir := t.TempDir()

	require.NoError(t, GeneratePluginWrappers(pluginDir))

	entries, err := os.ReadDir(pluginDir)
	require.NoError(t, err)
	assert.Empty(t, entries)
}

func TestGeneratePluginWrappers_PicksHighestVersion(t *testing.T) {
	pluginDir := t.TempDir()

	for _, ver := range []string{"v0.1.0", "v0.2.0"} {
		writeFakePlugin(t, pluginDir, "my-plugin", ver)
	}

	require.NoError(t, GeneratePluginWrappers(pluginDir))

	content, err := os.ReadFile(filepath.Join(pluginDir, "MyPlugin.pkl"))
	require.NoError(t, err)
	assert.Contains(t, string(content), `extends "./my-plugin/v0.2.0/schema/Config.pkl"`)
}

func TestGeneratePluginWrappers_SkipsNonDirectoryEntries(t *testing.T) {
	pluginDir := t.TempDir()

	require.NoError(t, os.WriteFile(filepath.Join(pluginDir, "readme.txt"), []byte("not a plugin"), 0644))

	require.NoError(t, GeneratePluginWrappers(pluginDir))
}

func TestGeneratePluginWrappers_FollowsSymlinkedPluginDir(t *testing.T) {
	wrapperDir := t.TempDir()
	source := t.TempDir()

	writeFakePlugin(t, source, "aws", "v0.1.6")
	require.NoError(t, os.Symlink(filepath.Join(source, "aws"), filepath.Join(wrapperDir, "aws")))

	require.NoError(t, GeneratePluginWrappers(wrapperDir))

	content, err := os.ReadFile(filepath.Join(wrapperDir, "Aws.pkl"))
	require.NoError(t, err, "wrapper must be generated even when the plugin dir is a symlink")
	assert.Contains(t, string(content), `extends "./aws/v0.1.6/schema/Config.pkl"`)
}

func TestGeneratePluginWrappers_RemovesStaleAutoGeneratedWrappers(t *testing.T) {
	wrapperDir := t.TempDir()
	writeFakePlugin(t, wrapperDir, "aws", "v0.1.6")

	require.NoError(t, GeneratePluginWrappers(wrapperDir))
	require.FileExists(t, filepath.Join(wrapperDir, "Aws.pkl"))

	require.NoError(t, os.RemoveAll(filepath.Join(wrapperDir, "aws")))
	require.NoError(t, GeneratePluginWrappers(wrapperDir))

	_, err := os.Stat(filepath.Join(wrapperDir, "Aws.pkl"))
	assert.True(t, os.IsNotExist(err), "stale auto-generated wrapper should have been removed")
}

func TestGeneratePluginWrappers_PreservesHandWrittenWrappers(t *testing.T) {
	wrapperDir := t.TempDir()
	handWritten := filepath.Join(wrapperDir, "Custom.pkl")
	require.NoError(t, os.WriteFile(handWritten, []byte("amends \"foo:/Bar.pkl\"\n"), 0644))

	require.NoError(t, GeneratePluginWrappers(wrapperDir))

	_, err := os.Stat(handWritten)
	assert.NoError(t, err, "hand-written wrapper without auto-generated header must not be deleted")
}

func TestPluginsSchemeOption_CreatesWrapperDirOnFreshInstall(t *testing.T) {
	tmp := t.TempDir()
	wrapperDir := filepath.Join(tmp, "home", ".pel", "formae", "plugins")
	systemDir := filepath.Join(tmp, "opt", "pel", "formae", "plugins")
	writeFakePlugin(t, systemDir, "aws", "v0.1.6")

	opt, err := pluginsSchemeOption(wrapperDir, fakeExeForSystemDir(t, systemDir))
	require.NoError(t, err)
	require.NotNil(t, opt, "expected a plugins:/ FS option even when wrapperDir didn't pre-exist")

	info, err := os.Stat(wrapperDir)
	require.NoError(t, err, "wrapperDir must be created on demand")
	assert.True(t, info.IsDir())

	// System plugin must be mirrored as a symlink so it resolves through plugins:/.
	link := filepath.Join(wrapperDir, "aws")
	target, err := os.Readlink(link)
	require.NoError(t, err, "system plugin must be symlinked into wrapperDir")
	assert.Equal(t, filepath.Join(systemDir, "aws"), target)

	// Wrapper must use a relative path (PKL refuses cross-scheme imports).
	wrapperContent, err := os.ReadFile(filepath.Join(wrapperDir, "Aws.pkl"))
	require.NoError(t, err)
	assert.Contains(t, string(wrapperContent), `extends "./aws/v0.1.6/schema/Config.pkl"`)
}

func TestPluginsSchemeOption_NoWrapperDirHint(t *testing.T) {
	opt, err := pluginsSchemeOption("", "/opt/pel/bin/formae")
	require.NoError(t, err)
	assert.Nil(t, opt, "no wrapperDir means no plugins:/ scheme")
}

func TestPluginsSchemeOption_DevPluginsOverrideSystem(t *testing.T) {
	tmp := t.TempDir()
	wrapperDir := filepath.Join(tmp, "home", ".pel", "formae", "plugins")
	systemDir := filepath.Join(tmp, "opt", "pel", "formae", "plugins")
	require.NoError(t, os.MkdirAll(wrapperDir, 0755))

	writeFakePlugin(t, wrapperDir, "aws", "v0.1.6")
	writeFakePlugin(t, systemDir, "aws", "v9.9.9")
	writeFakePlugin(t, systemDir, "azure", "v0.2.0")

	opt, err := pluginsSchemeOption(wrapperDir, fakeExeForSystemDir(t, systemDir))
	require.NoError(t, err)
	require.NotNil(t, opt)

	// aws was already a real dir under wrapperDir, so it must NOT have been
	// turned into a symlink to systemDir.
	awsInfo, err := os.Lstat(filepath.Join(wrapperDir, "aws"))
	require.NoError(t, err)
	assert.False(t, awsInfo.Mode()&os.ModeSymlink != 0,
		"dev plugin under wrapperDir must not be replaced with a system symlink")

	awsContent, err := os.ReadFile(filepath.Join(wrapperDir, "Aws.pkl"))
	require.NoError(t, err)
	assert.Contains(t, string(awsContent), `extends "./aws/v0.1.6/schema/Config.pkl"`)

	// azure was only in systemDir, so it should have been mirrored.
	azureLink, err := os.Readlink(filepath.Join(wrapperDir, "azure"))
	require.NoError(t, err)
	assert.Equal(t, filepath.Join(systemDir, "azure"), azureLink)

	azureContent, err := os.ReadFile(filepath.Join(wrapperDir, "Azure.pkl"))
	require.NoError(t, err)
	assert.Contains(t, string(azureContent), `extends "./azure/v0.2.0/schema/Config.pkl"`)
}

func TestPluginsSchemeOption_PrunesSymlinksToRemovedSystemPlugins(t *testing.T) {
	tmp := t.TempDir()
	wrapperDir := filepath.Join(tmp, "home", ".pel", "formae", "plugins")
	systemDir := filepath.Join(tmp, "opt", "pel", "formae", "plugins")
	writeFakePlugin(t, systemDir, "aws", "v0.1.6")
	writeFakePlugin(t, systemDir, "ovh", "v0.1.0")

	exe := fakeExeForSystemDir(t, systemDir)

	// First run mirrors both plugins and records them in the manifest.
	_, err := pluginsSchemeOption(wrapperDir, exe)
	require.NoError(t, err)
	require.FileExists(t, filepath.Join(wrapperDir, "ovh"))

	// ovh disappears from the system tree. Second run must reclaim our symlink.
	require.NoError(t, os.RemoveAll(filepath.Join(systemDir, "ovh")))
	_, err = pluginsSchemeOption(wrapperDir, exe)
	require.NoError(t, err)

	_, err = os.Lstat(filepath.Join(wrapperDir, "ovh"))
	assert.True(t, os.IsNotExist(err), "managed symlink to a removed system plugin must be pruned")

	awsLink, err := os.Readlink(filepath.Join(wrapperDir, "aws"))
	require.NoError(t, err, "still-present system plugin must remain symlinked")
	assert.Equal(t, filepath.Join(systemDir, "aws"), awsLink)
}

func TestPluginsSchemeOption_RemirrorsAcrossInstallRootUpgrade(t *testing.T) {
	tmp := t.TempDir()
	wrapperDir := filepath.Join(tmp, "home", ".pel", "formae", "plugins")
	oldSystemDir := filepath.Join(tmp, "opt", "pel-v1", "formae", "plugins")
	newSystemDir := filepath.Join(tmp, "opt", "pel-v2", "formae", "plugins")
	writeFakePlugin(t, oldSystemDir, "aws", "v0.1.6")
	writeFakePlugin(t, newSystemDir, "aws", "v0.1.7")

	// Simulate first run with the old install root.
	_, err := pluginsSchemeOption(wrapperDir, fakeExeForSystemDir(t, oldSystemDir))
	require.NoError(t, err)

	link := filepath.Join(wrapperDir, "aws")
	target, err := os.Readlink(link)
	require.NoError(t, err)
	require.Equal(t, filepath.Join(oldSystemDir, "aws"), target)

	// Now the binary moves to a new install root. The old symlink survives
	// from the previous run and would silently keep importing old plugins.
	_, err = pluginsSchemeOption(wrapperDir, fakeExeForSystemDir(t, newSystemDir))
	require.NoError(t, err)

	target, err = os.Readlink(link)
	require.NoError(t, err, "symlink should be repointed at the new install root")
	assert.Equal(t, filepath.Join(newSystemDir, "aws"), target)

	wrapperContent, err := os.ReadFile(filepath.Join(wrapperDir, "Aws.pkl"))
	require.NoError(t, err)
	assert.Contains(t, string(wrapperContent), `extends "./aws/v0.1.7/schema/Config.pkl"`,
		"wrapper must reflect the version found via the refreshed symlink")
}

func TestPluginsSchemeOption_LeavesUserSymlinkToOtherFormaeTreeAlone(t *testing.T) {
	tmp := t.TempDir()
	wrapperDir := filepath.Join(tmp, "home", ".pel", "formae", "plugins")
	systemDir := filepath.Join(tmp, "opt", "pel", "formae", "plugins")
	require.NoError(t, os.MkdirAll(systemDir, 0755))

	require.NoError(t, os.MkdirAll(wrapperDir, 0755))
	// User intentionally points wrapperDir/aws at a *different* formae tree
	// (e.g. a checkout). The target shape matches our system-mirror layout,
	// but the link is not in our manifest, so we must leave it alone.
	otherTree := filepath.Join(tmp, "checkout", "formae", "plugins", "aws")
	require.NoError(t, os.MkdirAll(otherTree, 0755))
	require.NoError(t, os.Symlink(otherTree, filepath.Join(wrapperDir, "aws")))

	_, err := pluginsSchemeOption(wrapperDir, fakeExeForSystemDir(t, systemDir))
	require.NoError(t, err)

	target, err := os.Readlink(filepath.Join(wrapperDir, "aws"))
	require.NoError(t, err, "user-managed symlink must not be pruned, even when it has system-mirror shape")
	assert.Equal(t, otherTree, target)
}

func TestPluginsSchemeOption_DropsOwnershipWhenUserOverwritesOurSymlink(t *testing.T) {
	tmp := t.TempDir()
	wrapperDir := filepath.Join(tmp, "home", ".pel", "formae", "plugins")
	systemDir := filepath.Join(tmp, "opt", "pel", "formae", "plugins")
	writeFakePlugin(t, systemDir, "aws", "v0.1.6")

	// First run mirrors and records aws.
	_, err := pluginsSchemeOption(wrapperDir, fakeExeForSystemDir(t, systemDir))
	require.NoError(t, err)

	// User replaces our symlink with their own pointing somewhere else.
	custom := filepath.Join(tmp, "custom", "aws")
	require.NoError(t, os.MkdirAll(custom, 0755))
	require.NoError(t, os.Remove(filepath.Join(wrapperDir, "aws")))
	require.NoError(t, os.Symlink(custom, filepath.Join(wrapperDir, "aws")))

	// Second run must observe the divergence, drop ownership, and leave the link alone.
	_, err = pluginsSchemeOption(wrapperDir, fakeExeForSystemDir(t, systemDir))
	require.NoError(t, err)

	target, err := os.Readlink(filepath.Join(wrapperDir, "aws"))
	require.NoError(t, err)
	assert.Equal(t, custom, target,
		"once the on-disk target diverges from the manifest, we treat the entry as user-managed")
}

func TestPluginsSchemeOption_LeavesUnrelatedSymlinksAlone(t *testing.T) {
	tmp := t.TempDir()
	wrapperDir := filepath.Join(tmp, "home", ".pel", "formae", "plugins")
	systemDir := filepath.Join(tmp, "opt", "pel", "formae", "plugins")
	require.NoError(t, os.MkdirAll(systemDir, 0755))

	require.NoError(t, os.MkdirAll(wrapperDir, 0755))
	customTarget := filepath.Join(tmp, "elsewhere")
	require.NoError(t, os.Symlink(customTarget, filepath.Join(wrapperDir, "custom")))

	_, err := pluginsSchemeOption(wrapperDir, fakeExeForSystemDir(t, systemDir))
	require.NoError(t, err)

	target, err := os.Readlink(filepath.Join(wrapperDir, "custom"))
	require.NoError(t, err, "user-managed symlink to a non-system path must be preserved")
	assert.Equal(t, customTarget, target)
}

func TestToPascalCase(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"auth-basic", "AuthBasic"},
		{"gcp", "Gcp"},
		{"my-cool-plugin", "MyCoolPlugin"},
		{"aws", "Aws"},
		{"a", "A"},
	}

	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			assert.Equal(t, tt.expected, toPascalCase(tt.input))
		})
	}
}

func TestFindHighestVersionDir(t *testing.T) {
	dir := t.TempDir()

	assert.Equal(t, "", findHighestVersionDir(dir))

	for _, v := range []string{"v0.1.0", "v0.2.0", "v0.1.5"} {
		require.NoError(t, os.MkdirAll(filepath.Join(dir, v), 0755))
	}

	assert.Equal(t, "v0.2.0", findHighestVersionDir(dir))
}

func TestFindHighestVersionDir_NonExistentDir(t *testing.T) {
	assert.Equal(t, "", findHighestVersionDir("/nonexistent/path"))
}
