// © 2026 Platform Engineering Labs Inc.
//
// SPDX-License-Identifier: FSL-1.1-ALv2

package login

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"slices"
	"strings"

	"github.com/platform-engineering-labs/formae/internal/cli/app"
	pkgmodel "github.com/platform-engineering-labs/formae/pkg/model"
)

// Rendering and publication turn one installation into one file on disk.
//
// The file a run writes must never be able to clobber, or be confused with, a
// file the user wrote. Profiles get copied, hand-edited, and hand-authored,
// and the authority to remove one comes from a ledger record saying "this run
// wrote exactly these bytes at this name" — a record that is only worth
// anything if publication cannot overwrite someone else's file and cannot
// leave a half-written file that a later run mistakes for its own. So a
// profile is rendered into a temp file beside its destination, loaded back
// through the config loader to prove it resolves to the installation it was
// rendered for, and only then hard-linked into place: os.Link is atomic and
// fails outright when the destination exists, so the destination is never
// observable in a partially written state and an existing name is refused
// rather than replaced.
//
// The auth block is the other half of "correct". It reproduces the oidc auth
// plugin's CLI config class, and nothing checks that coupling at compile
// time: a block missing a field the plugin's reader requires does not
// produce a profile with a missing field, it produces a profile that never
// authenticates. The rendered block is a Dynamic and not an instance of that
// class, so it inherits none of the class's defaults — every key the profile
// should carry is written here by value, and a key left out is simply a key
// the profile does not have.

// generatedProfileMode is the permission a generated profile carries. It is
// tighter than the 0644 of a stub the user is about to edit: this file is
// machine-generated, per-user, never shared, and carries a block that came
// from a credential-adjacent plugin.
const generatedProfileMode os.FileMode = 0o600

// tempNamePrefix and tempNameSuffix bracket the 16 hex characters of a
// publication temp file's name. The result is a dotfile with a .pkl
// extension that no profile name can collide with, since store.ValidateName
// accepts neither a leading dot nor a hyphen-free hex body containing one.
const (
	tempNamePrefix = ".tmp-"
	tempNameSuffix = ".pkl"
)

// fingerprintPrefix names the digest algorithm inside a fingerprint, so a
// record written today says what produced it rather than relying on length.
const fingerprintPrefix = "sha256:"

// renderedAuthKeys is exactly the set of keys a generated auth block carries,
// in the order it writes them. It is also the set unknownAuthKeysWarning
// measures a source block against, so the two can never drift apart.
var renderedAuthKeys = []string{"type", "role", "issuer", "clientId", "scopes"}

// profileTemplate is the whole of a generated profile. Its comment is the
// only thing a reader of the file has to go on, so it says what wrote the
// file and what happens to an edit.
const profileTemplate = `amends "formae:/Config.pkl"

// Generated by ` + "`formae login`" + ` for one hosted installation. Signing in again
// refreshes it, and formae removes it once your access to that installation
// goes away.
//
// Your edits are preserved. formae recognises this file by its exact contents,
// so changing anything in it — including this comment — makes it yours: formae
// stops updating it, never removes it, and keeping it current is then up to
// you. To hand it back, delete this file and sign in again.
//
// See https://docs.formae.io for the full list of options.

cli {
    connection = new Hosted {
        endpoint = %s
        installation = %s
        auth = new Dynamic {
            type = %s
            role = %s
            issuer = %s
            clientId = %s
            scopes = %s
        }
    }
}
`

// renderProfile returns the bytes of a generated hosted profile for one
// installation.
//
// type, role, and issuer are written exactly as the gate validated them and
// are never invented: role in particular is mandatory, because the plugin's
// config reader reads it first and errors when it is absent, so a profile
// without one authenticates against nothing. clientId and scopes are the
// source block's values when it named them and the plugin's documented
// defaults, written by value, when it did not. scopes is a single
// space-separated string: the plugin's wire struct types it as a string, so a
// Listing would arrive as a JSON array and fail to unmarshal.
//
// Any field the source block carried beyond these is dropped by construction,
// since the renderer writes from typed fields rather than copying opaque
// JSON. unknownAuthKeysWarning names what was dropped.
//
// It returns bytes and no error on purpose: every value it writes is a string
// it can always escape into a Pkl literal, so there is no such thing as an
// unrenderable input here. Whether the bytes are *usable* is a separate
// question with a separate answer — profileVerifier loads them back before
// they are published — and folding the two together would invite a caller to
// treat a nil error as proof the profile works.
func renderProfile(endpoint, installation string, auth cliAuthBlock) []byte {
	clientID := auth.ClientID
	if clientID == "" {
		clientID = defaultOidcClientID
	}
	scopes := auth.Scopes
	if scopes == "" {
		scopes = defaultOidcScopes
	}

	return []byte(fmt.Sprintf(profileTemplate,
		pklString(endpoint),
		pklString(installation),
		pklString(auth.Type),
		pklString(auth.Role),
		pklString(auth.Issuer),
		pklString(clientID),
		pklString(scopes),
	))
}

// pklString renders s as a Pkl string literal.
//
// Pkl's escapes are not Go's: a backslash introduces an escape sequence and
// `\(` introduces string interpolation, so an unescaped backslash in a value
// can turn the rest of a literal into an expression. Escaping the backslash
// closes that on its own; the quote, the line breaks, and the tab are escaped
// because a raw one either ends the literal or is not a literal character at
// all. Everything else below the printable range is written as a codepoint
// escape rather than emitted raw.
func pklString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch {
		case r == '\\':
			b.WriteString(`\\`)
		case r == '"':
			b.WriteString(`\"`)
		case r == '\n':
			b.WriteString(`\n`)
		case r == '\r':
			b.WriteString(`\r`)
		case r == '\t':
			b.WriteString(`\t`)
		case r < 0x20 || r == 0x7f:
			fmt.Fprintf(&b, `\u{%x}`, r)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// unknownAuthKeysWarning returns a warning naming the keys of the source auth
// block that a generated profile does not carry, or "" when it carries all of
// them.
//
// Only the names are reported, never the values: the block that named them is
// the one that may hold a setting belonging to another system, the same
// reason the gate never repeats a value back. A block that will not decode
// yields no warning — it is not this function's job to report that, and the
// gate has already refused it.
func unknownAuthKeysWarning(raw json.RawMessage) string {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(raw, &fields); err != nil {
		return ""
	}

	unknown := make([]string, 0, len(fields))
	for key := range fields {
		if !slices.Contains(renderedAuthKeys, key) {
			unknown = append(unknown, key)
		}
	}
	if len(unknown) == 0 {
		return ""
	}
	slices.Sort(unknown)

	return fmt.Sprintf(
		"this profile's auth block sets %s, which a generated profile does not carry; "+
			"generated profiles carry only %s, so those settings will not appear in them",
		strings.Join(quoted(unknown), ", "), strings.Join(quoted(renderedAuthKeys), ", "))
}

// quoted returns keys with each one quoted, so a name that is empty or full
// of spaces is still visible in a message.
func quoted(keys []string) []string {
	out := make([]string, 0, len(keys))
	for _, key := range keys {
		out = append(out, fmt.Sprintf("%q", key))
	}
	return out
}

// fingerprint returns the content fingerprint of b: the digest a ledger entry
// records, and the whole proof that a file on disk is one this formae wrote.
func fingerprint(b []byte) string {
	sum := sha256.Sum256(b)
	return fingerprintPrefix + hex.EncodeToString(sum[:])
}

// errNotRegularFile reports a path that is not a regular file, so a caller
// can tell "this is not a file we could ever own" from a filesystem failure.
var errNotRegularFile = errors.New("not a regular file")

// statAndDigest opens path once and returns its FileInfo and fingerprint from
// that single descriptor, so the bytes hashed and the file identified are the
// same file. Identifying a file through one path lookup and hashing it
// through another leaves a window for the two to be different files.
//
// Only a regular file is accepted. The check is made twice against the one
// open handle: an Lstat before the open refuses a symlink outright rather
// than following it to a regular file, and the handle's own Stat refuses
// anything else. Requiring the two to describe the same file closes the gap
// between them, so a path swapped after the Lstat is refused rather than read.
func statAndDigest(path string) (os.FileInfo, string, error) {
	linkInfo, err := os.Lstat(path)
	if err != nil {
		return nil, "", fmt.Errorf("stat %s: %w", path, err)
	}
	if !linkInfo.Mode().IsRegular() {
		return nil, "", fmt.Errorf("%s is %w", path, errNotRegularFile)
	}

	f, err := os.Open(path)
	if err != nil {
		return nil, "", fmt.Errorf("open %s: %w", path, err)
	}
	defer func() { _ = f.Close() }()

	info, err := f.Stat()
	if err != nil {
		return nil, "", fmt.Errorf("stat %s: %w", path, err)
	}
	if !info.Mode().IsRegular() {
		return nil, "", fmt.Errorf("%s is %w", path, errNotRegularFile)
	}
	if !os.SameFile(linkInfo, info) {
		return nil, "", fmt.Errorf("%s changed while it was being read", path)
	}

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return nil, "", fmt.Errorf("read %s: %w", path, err)
	}
	return info, fingerprintPrefix + hex.EncodeToString(h.Sum(nil)), nil
}

// errNameTaken reports that the destination name is already occupied by a
// file this run did not write. It is never a reason to write anything.
var errNameTaken = errors.New("a file already exists at that profile name")

// linkFile is a package seam so a test can exercise the path taken on a
// filesystem that refuses hard links, which cannot otherwise be reached
// without a second filesystem. Nothing but a test ever assigns it, so
// production always runs os.Link.
var linkFile = os.Link

// publish puts content at destPath by linking tempPath onto it, and returns
// errNameTaken when the name is already occupied.
//
// The two ways link can fail mean opposite things. EEXIST means the
// destination exists — someone else's file, or one this run already
// published — and is reported, never worked around: falling back there would
// race whatever is at that name. Any other failure means hard links are
// unavailable rather than unwanted: network mounts, restrictive mount
// options, and some Windows configurations refuse link while open and rename
// work fine, and treating that as fatal would make generated profiles
// impossible on those machines. The fallback writes the destination with
// O_CREATE|O_EXCL, which is equally incapable of clobbering a user's file.
// content must therefore be the bytes that were written to tempPath and
// verified there, since on that path they are what reaches the destination.
//
// The fallback does cost something, and it is only the link path that is free
// of it: linking publishes a file that is already complete, so the
// destination never exists half-written, whereas a crash midway through the
// fallback's write can leave a truncated file at a managed name. That is
// contained rather than harmless — such a file matches no fingerprint any
// ledger entry records, so no later run adopts it and no later run removes
// it, and it is the user's to delete — but it is not a guarantee the fallback
// path can make.
//
// The temp file is left where it is on both paths. It is the witness a
// resumed run needs: a temp file that is still the same file as the
// destination is proof that this publication happened, which is the one thing
// a crash between linking and recording the result would otherwise destroy.
// Removing it is the ledger's business, once the record it belongs to says so.
func publish(tempPath, destPath string, content []byte, mode os.FileMode) error {
	// The destination shares the temp file's inode, and so its permissions:
	// setting the mode here is what makes it hold on the published file.
	if err := os.Chmod(tempPath, mode); err != nil {
		return fmt.Errorf("set mode on %s: %w", tempPath, err)
	}

	linkErr := linkFile(tempPath, destPath)
	switch {
	case linkErr == nil:
		return nil
	case errors.Is(linkErr, os.ErrExist):
		return fmt.Errorf("%w: %s", errNameTaken, destPath)
	}

	f, err := os.OpenFile(destPath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, mode)
	if err != nil {
		if errors.Is(err, os.ErrExist) {
			return fmt.Errorf("%w: %s", errNameTaken, destPath)
		}
		return fmt.Errorf("write %s (hard links are unavailable here: %v): %w", destPath, linkErr, err)
	}
	// Set through the descriptor rather than the path, so the mode lands on
	// the file just created whatever the process umask stripped from it and
	// whatever appears at that name afterwards.
	if err := f.Chmod(mode); err != nil {
		_ = f.Close()
		return fmt.Errorf("set mode on %s: %w", destPath, err)
	}
	if _, err := f.Write(content); err != nil {
		_ = f.Close()
		return fmt.Errorf("write %s: %w", destPath, err)
	}
	if err := f.Close(); err != nil {
		return fmt.Errorf("close %s: %w", destPath, err)
	}
	return nil
}

// newTempName returns the name of a publication temp file: a dotfile no
// profile name can equal, carrying 16 random hex characters so two formae
// processes writing the same profile at the same time cannot choose the same
// one. The randomness is cryptographic because the name is created in a
// directory whose contents are guessable otherwise.
func newTempName() (string, error) {
	var b [8]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", fmt.Errorf("generate a temp profile name: %w", err)
	}
	return tempNamePrefix + hex.EncodeToString(b[:]) + tempNameSuffix, nil
}

// profileVerifier loads a rendered profile by explicit path and checks it
// resolves to the intended hosted connection. Verifying before publishing is
// what turns "the renderer emits valid Pkl" and "the schema still accepts
// this shape" into invariants this command checks rather than assumes, so a
// broken profile costs a skipped installation and a message instead of
// breaking the user's next command.
type profileVerifier interface {
	Verify(path, endpoint, installation string) error
}

// configVerifier verifies a profile by loading it through the same config
// loader every formae command loads a profile with, so what is verified is
// what a later command will read — not a second parser that could accept what
// the real one rejects.
type configVerifier struct{}

// newProfileVerifier returns the verifier used in production.
func newProfileVerifier() profileVerifier {
	return configVerifier{}
}

// Verify loads the profile at path and reports whether it resolves to the
// hosted connection it was rendered for.
//
// The path is passed explicitly and the active-profile pointer is never
// consulted: the file being verified is a temp file that is deliberately not
// any profile the store knows about, and resolving through the pointer would
// verify whichever profile happens to be active instead.
func (configVerifier) Verify(path, endpoint, installation string) error {
	a := &app.App{}
	if err := a.LoadConfig(path, ""); err != nil {
		return fmt.Errorf("the generated profile does not load: %w", err)
	}

	hosted, ok := a.Config.Cli.Connection.(*pkgmodel.HostedConnection)
	if !ok || hosted == nil {
		return fmt.Errorf("the generated profile does not configure a hosted connection")
	}
	if hosted.Endpoint != endpoint {
		return fmt.Errorf("the generated profile addresses %s rather than %s", hosted.Endpoint, endpoint)
	}
	if hosted.Installation != installation {
		return fmt.Errorf("the generated profile addresses installation %s rather than %s",
			hosted.Installation, installation)
	}
	return nil
}
