-- © 2026 Platform Engineering Labs Inc.
-- SPDX-License-Identifier: FSL-1.1-ALv2
-- +goose Up
-- Resource predicate scopes are advanced under the existing URI serialization,
-- before the common sorted revision-lock pass. Full URI history participates.
-- Target identities use physical target equality, also conservatively covering
-- embedded Target values used by in-memory maps. SQL Server MAX retains long
-- JSON targets; registration uses a locked insert recheck, never truncation.
-- Resource identity uses the physical ksuid column, which loaders restore over JSON.
CREATE TABLE admission_inventory_targets (label TEXT NOT NULL, guard_key TEXT COLLATE "C" NOT NULL PRIMARY KEY DEFAULT ('admission:inventory-target:' || gen_random_uuid()::text));
CREATE TABLE admission_resource_ids (label TEXT NOT NULL PRIMARY KEY, guard_key TEXT COLLATE "C" NOT NULL UNIQUE DEFAULT ('admission:resource-id:' || gen_random_uuid()::text));
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION admission_resources_insert() RETURNS trigger LANGUAGE plpgsql VOLATILE AS $$
DECLARE k TEXT; target_label TEXT;
BEGIN
INSERT INTO admission_resource_uris(uri) SELECT DISTINCT uri FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) affected ON CONFLICT(uri) DO NOTHING;
FOR k IN SELECT u.guard_key FROM admission_resource_uris u JOIN (SELECT DISTINCT uri FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) affected) a ON a.uri=u.uri ORDER BY u.guard_key COLLATE "C" LOOP
INSERT INTO admission_revisions(guard_key,revision) VALUES (k,1) ON CONFLICT(guard_key) DO UPDATE SET revision=admission_revisions.revision+1;
END LOOP;
FOR target_label IN SELECT DISTINCT label FROM (SELECT r.target AS label FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Target') FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT h.target FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Target') FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri) scopes WHERE label IS NOT NULL ORDER BY label LOOP
IF NOT EXISTS (SELECT 1 FROM admission_inventory_targets WHERE label=target_label) THEN
LOCK TABLE admission_inventory_targets IN SHARE ROW EXCLUSIVE MODE;
INSERT INTO admission_inventory_targets(label) SELECT target_label WHERE NOT EXISTS (SELECT 1 FROM admission_inventory_targets WHERE label=target_label);
END IF;
END LOOP;
INSERT INTO admission_resource_ids(label) SELECT DISTINCT label FROM (SELECT r.ksuid AS label FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT h.ksuid FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri) scopes WHERE label IS NOT NULL ON CONFLICT(label) DO NOTHING;
INSERT INTO admission_stack_labels(label) SELECT DISTINCT label FROM (SELECT r.stack AS label FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Stack') FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT h.stack FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Stack') FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri) labels WHERE label IS NOT NULL ON CONFLICT(label) DO NOTHING;
FOR k IN SELECT guard_key FROM (SELECT l.guard_key FROM admission_stack_labels l JOIN (SELECT r.stack AS label FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Stack') FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT h.stack FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Stack') FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri) x ON l.label=x.label
UNION
SELECT p.guard_key FROM admission_inventory_targets p JOIN (SELECT r.target AS label FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Target') FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT h.target FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Target') FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri) x ON p.label=x.label
UNION
SELECT p.guard_key FROM admission_resource_ids p JOIN (SELECT r.ksuid AS label FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT h.ksuid FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri) x ON p.label=x.label
UNION
SELECT CASE WHEN RTRIM(s.id) ~ '^[A-Za-z0-9_-]{1,128}$' THEN 'admission:stack:' || RTRIM(s.id) ELSE 'admission:stack:exceptional' END AS guard_key FROM stacks s JOIN (SELECT r.stack AS label FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Stack') FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT h.stack FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Stack') FROM resources h JOIN (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri) x ON s.label=x.label
UNION
SELECT 'admission:topology' AS guard_key WHERE EXISTS (SELECT 1 FROM (SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r WHERE (CAST(r.data AS TEXT) LIKE '%$ref%' OR CAST(r.data AS TEXT) LIKE '%$gen%' OR CAST(r.data AS TEXT) LIKE '%' || chr(92) || '%') OR cardinality(r.refs)>0 OR EXISTS (SELECT 1 FROM resources h WHERE h.uri=r.uri AND ((CAST(h.data AS TEXT) LIKE '%$ref%' OR CAST(h.data AS TEXT) LIKE '%$gen%' OR CAST(h.data AS TEXT) LIKE '%' || chr(92) || '%') OR cardinality(h.refs)>0)))) keys ORDER BY guard_key COLLATE "C" LOOP
INSERT INTO admission_revisions(guard_key,revision) VALUES (k,1) ON CONFLICT(guard_key) DO UPDATE SET revision=admission_revisions.revision+1;
END LOOP;
RETURN NEW;
END $$;
-- +goose StatementEnd
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION admission_resources_update() RETURNS trigger LANGUAGE plpgsql VOLATILE AS $$
DECLARE k TEXT; target_label TEXT;
BEGIN
INSERT INTO admission_resource_uris(uri) SELECT DISTINCT uri FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) affected ON CONFLICT(uri) DO NOTHING;
FOR k IN SELECT u.guard_key FROM admission_resource_uris u JOIN (SELECT DISTINCT uri FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) affected) a ON a.uri=u.uri ORDER BY u.guard_key COLLATE "C" LOOP
INSERT INTO admission_revisions(guard_key,revision) VALUES (k,1) ON CONFLICT(guard_key) DO UPDATE SET revision=admission_revisions.revision+1;
END LOOP;
FOR target_label IN SELECT DISTINCT label FROM (SELECT r.target AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Target') FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT h.target FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Target') FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri) scopes WHERE label IS NOT NULL ORDER BY label LOOP
IF NOT EXISTS (SELECT 1 FROM admission_inventory_targets WHERE label=target_label) THEN
LOCK TABLE admission_inventory_targets IN SHARE ROW EXCLUSIVE MODE;
INSERT INTO admission_inventory_targets(label) SELECT target_label WHERE NOT EXISTS (SELECT 1 FROM admission_inventory_targets WHERE label=target_label);
END IF;
END LOOP;
INSERT INTO admission_resource_ids(label) SELECT DISTINCT label FROM (SELECT r.ksuid AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT h.ksuid FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri) scopes WHERE label IS NOT NULL ON CONFLICT(label) DO NOTHING;
INSERT INTO admission_stack_labels(label) SELECT DISTINCT label FROM (SELECT r.stack AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Stack') FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Stack') FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri) labels WHERE label IS NOT NULL ON CONFLICT(label) DO NOTHING;
FOR k IN SELECT guard_key FROM (SELECT l.guard_key FROM admission_stack_labels l JOIN (SELECT r.stack AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Stack') FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Stack') FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri) x ON l.label=x.label
UNION
SELECT p.guard_key FROM admission_inventory_targets p JOIN (SELECT r.target AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Target') FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT h.target FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Target') FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri) x ON p.label=x.label
UNION
SELECT p.guard_key FROM admission_resource_ids p JOIN (SELECT r.ksuid AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT h.ksuid FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri) x ON p.label=x.label
UNION
SELECT CASE WHEN RTRIM(s.id) ~ '^[A-Za-z0-9_-]{1,128}$' THEN 'admission:stack:' || RTRIM(s.id) ELSE 'admission:stack:exceptional' END AS guard_key FROM stacks s JOIN (SELECT r.stack AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Stack') FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Stack') FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri) x ON s.label=x.label
UNION
SELECT 'admission:topology' AS guard_key WHERE EXISTS (SELECT 1 FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.target AS target, NEW.ksuid AS ksuid, NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r WHERE (CAST(r.data AS TEXT) LIKE '%$ref%' OR CAST(r.data AS TEXT) LIKE '%$gen%' OR CAST(r.data AS TEXT) LIKE '%' || chr(92) || '%') OR cardinality(r.refs)>0 OR EXISTS (SELECT 1 FROM resources h WHERE h.uri=r.uri AND ((CAST(h.data AS TEXT) LIKE '%$ref%' OR CAST(h.data AS TEXT) LIKE '%$gen%' OR CAST(h.data AS TEXT) LIKE '%' || chr(92) || '%') OR cardinality(h.refs)>0)))) keys ORDER BY guard_key COLLATE "C" LOOP
INSERT INTO admission_revisions(guard_key,revision) VALUES (k,1) ON CONFLICT(guard_key) DO UPDATE SET revision=admission_revisions.revision+1;
END LOOP;
RETURN NEW;
END $$;
-- +goose StatementEnd
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION admission_resources_delete() RETURNS trigger LANGUAGE plpgsql VOLATILE AS $$
DECLARE k TEXT; target_label TEXT;
BEGIN
INSERT INTO admission_resource_uris(uri) SELECT DISTINCT uri FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) affected ON CONFLICT(uri) DO NOTHING;
FOR k IN SELECT u.guard_key FROM admission_resource_uris u JOIN (SELECT DISTINCT uri FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) affected) a ON a.uri=u.uri ORDER BY u.guard_key COLLATE "C" LOOP
INSERT INTO admission_revisions(guard_key,revision) VALUES (k,1) ON CONFLICT(guard_key) DO UPDATE SET revision=admission_revisions.revision+1;
END LOOP;
FOR target_label IN SELECT DISTINCT label FROM (SELECT r.target AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Target') FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r UNION SELECT h.target FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Target') FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r ON h.uri=r.uri) scopes WHERE label IS NOT NULL ORDER BY label LOOP
IF NOT EXISTS (SELECT 1 FROM admission_inventory_targets WHERE label=target_label) THEN
LOCK TABLE admission_inventory_targets IN SHARE ROW EXCLUSIVE MODE;
INSERT INTO admission_inventory_targets(label) SELECT target_label WHERE NOT EXISTS (SELECT 1 FROM admission_inventory_targets WHERE label=target_label);
END IF;
END LOOP;
INSERT INTO admission_resource_ids(label) SELECT DISTINCT label FROM (SELECT r.ksuid AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r UNION SELECT h.ksuid FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r ON h.uri=r.uri) scopes WHERE label IS NOT NULL ON CONFLICT(label) DO NOTHING;
INSERT INTO admission_stack_labels(label) SELECT DISTINCT label FROM (SELECT r.stack AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Stack') FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Stack') FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r ON h.uri=r.uri) labels WHERE label IS NOT NULL ON CONFLICT(label) DO NOTHING;
FOR k IN SELECT guard_key FROM (SELECT l.guard_key FROM admission_stack_labels l JOIN (SELECT r.stack AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Stack') FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Stack') FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r ON h.uri=r.uri) x ON l.label=x.label
UNION
SELECT p.guard_key FROM admission_inventory_targets p JOIN (SELECT r.target AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Target') FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r UNION SELECT h.target FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Target') FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r ON h.uri=r.uri) x ON p.label=x.label
UNION
SELECT p.guard_key FROM admission_resource_ids p JOIN (SELECT r.ksuid AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r UNION SELECT h.ksuid FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r ON h.uri=r.uri) x ON p.label=x.label
UNION
SELECT CASE WHEN RTRIM(s.id) ~ '^[A-Za-z0-9_-]{1,128}$' THEN 'admission:stack:' || RTRIM(s.id) ELSE 'admission:stack:exceptional' END AS guard_key FROM stacks s JOIN (SELECT r.stack AS label FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Stack') FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Stack') FROM resources h JOIN (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r ON h.uri=r.uri) x ON s.label=x.label
UNION
SELECT 'admission:topology' AS guard_key WHERE EXISTS (SELECT 1 FROM (SELECT OLD.target AS target, OLD.ksuid AS ksuid, OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r WHERE (CAST(r.data AS TEXT) LIKE '%$ref%' OR CAST(r.data AS TEXT) LIKE '%$gen%' OR CAST(r.data AS TEXT) LIKE '%' || chr(92) || '%') OR cardinality(r.refs)>0 OR EXISTS (SELECT 1 FROM resources h WHERE h.uri=r.uri AND ((CAST(h.data AS TEXT) LIKE '%$ref%' OR CAST(h.data AS TEXT) LIKE '%$gen%' OR CAST(h.data AS TEXT) LIKE '%' || chr(92) || '%') OR cardinality(h.refs)>0)))) keys ORDER BY guard_key COLLATE "C" LOOP
INSERT INTO admission_revisions(guard_key,revision) VALUES (k,1) ON CONFLICT(guard_key) DO UPDATE SET revision=admission_revisions.revision+1;
END LOOP;
RETURN OLD;
END $$;
-- +goose StatementEnd
-- +goose Down
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION admission_resources_insert() RETURNS trigger LANGUAGE plpgsql VOLATILE AS $$
DECLARE k TEXT;
BEGIN
INSERT INTO admission_resource_uris(uri) SELECT DISTINCT uri FROM (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) affected ON CONFLICT(uri) DO NOTHING;
FOR k IN SELECT u.guard_key FROM admission_resource_uris u JOIN (SELECT DISTINCT uri FROM (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) affected) a ON a.uri=u.uri ORDER BY u.guard_key COLLATE "C" LOOP
INSERT INTO admission_revisions(guard_key,revision) VALUES (k,1) ON CONFLICT(guard_key) DO UPDATE SET revision=admission_revisions.revision+1;
END LOOP;
INSERT INTO admission_stack_labels(label) SELECT DISTINCT label FROM (SELECT r.stack AS label FROM (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Stack') FROM (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT h.stack FROM resources h JOIN (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Stack') FROM resources h JOIN (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri) labels WHERE label IS NOT NULL ON CONFLICT(label) DO NOTHING;
FOR k IN SELECT guard_key FROM (SELECT l.guard_key FROM admission_stack_labels l JOIN (SELECT r.stack AS label FROM (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Stack') FROM (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT h.stack FROM resources h JOIN (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Stack') FROM resources h JOIN (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri) x ON l.label=x.label
UNION
SELECT CASE WHEN RTRIM(s.id) ~ '^[A-Za-z0-9_-]{1,128}$' THEN 'admission:stack:' || RTRIM(s.id) ELSE 'admission:stack:exceptional' END AS guard_key FROM stacks s JOIN (SELECT r.stack AS label FROM (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Stack') FROM (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT h.stack FROM resources h JOIN (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Stack') FROM resources h JOIN (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri) x ON s.label=x.label
UNION
SELECT 'admission:topology' AS guard_key WHERE EXISTS (SELECT 1 FROM (SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r WHERE (CAST(r.data AS TEXT) LIKE '%$ref%' OR CAST(r.data AS TEXT) LIKE '%$gen%' OR CAST(r.data AS TEXT) LIKE '%' || chr(92) || '%') OR cardinality(r.refs)>0 OR EXISTS (SELECT 1 FROM resources h WHERE h.uri=r.uri AND ((CAST(h.data AS TEXT) LIKE '%$ref%' OR CAST(h.data AS TEXT) LIKE '%$gen%' OR CAST(h.data AS TEXT) LIKE '%' || chr(92) || '%') OR cardinality(h.refs)>0)))) keys ORDER BY guard_key COLLATE "C" LOOP
INSERT INTO admission_revisions(guard_key,revision) VALUES (k,1) ON CONFLICT(guard_key) DO UPDATE SET revision=admission_revisions.revision+1;
END LOOP;
RETURN NEW;
END $$;
-- +goose StatementEnd
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION admission_resources_update() RETURNS trigger LANGUAGE plpgsql VOLATILE AS $$
DECLARE k TEXT;
BEGIN
INSERT INTO admission_resource_uris(uri) SELECT DISTINCT uri FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) affected ON CONFLICT(uri) DO NOTHING;
FOR k IN SELECT u.guard_key FROM admission_resource_uris u JOIN (SELECT DISTINCT uri FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) affected) a ON a.uri=u.uri ORDER BY u.guard_key COLLATE "C" LOOP
INSERT INTO admission_revisions(guard_key,revision) VALUES (k,1) ON CONFLICT(guard_key) DO UPDATE SET revision=admission_revisions.revision+1;
END LOOP;
INSERT INTO admission_stack_labels(label) SELECT DISTINCT label FROM (SELECT r.stack AS label FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Stack') FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Stack') FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri) labels WHERE label IS NOT NULL ON CONFLICT(label) DO NOTHING;
FOR k IN SELECT guard_key FROM (SELECT l.guard_key FROM admission_stack_labels l JOIN (SELECT r.stack AS label FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Stack') FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Stack') FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri) x ON l.label=x.label
UNION
SELECT CASE WHEN RTRIM(s.id) ~ '^[A-Za-z0-9_-]{1,128}$' THEN 'admission:stack:' || RTRIM(s.id) ELSE 'admission:stack:exceptional' END AS guard_key FROM stacks s JOIN (SELECT r.stack AS label FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Stack') FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Stack') FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r ON h.uri=r.uri) x ON s.label=x.label
UNION
SELECT 'admission:topology' AS guard_key WHERE EXISTS (SELECT 1 FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs UNION ALL SELECT NEW.stack AS stack, NEW.data AS data, NEW.uri AS uri, NEW.refs AS refs) r WHERE (CAST(r.data AS TEXT) LIKE '%$ref%' OR CAST(r.data AS TEXT) LIKE '%$gen%' OR CAST(r.data AS TEXT) LIKE '%' || chr(92) || '%') OR cardinality(r.refs)>0 OR EXISTS (SELECT 1 FROM resources h WHERE h.uri=r.uri AND ((CAST(h.data AS TEXT) LIKE '%$ref%' OR CAST(h.data AS TEXT) LIKE '%$gen%' OR CAST(h.data AS TEXT) LIKE '%' || chr(92) || '%') OR cardinality(h.refs)>0)))) keys ORDER BY guard_key COLLATE "C" LOOP
INSERT INTO admission_revisions(guard_key,revision) VALUES (k,1) ON CONFLICT(guard_key) DO UPDATE SET revision=admission_revisions.revision+1;
END LOOP;
RETURN NEW;
END $$;
-- +goose StatementEnd
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION admission_resources_delete() RETURNS trigger LANGUAGE plpgsql VOLATILE AS $$
DECLARE k TEXT;
BEGIN
INSERT INTO admission_resource_uris(uri) SELECT DISTINCT uri FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) affected ON CONFLICT(uri) DO NOTHING;
FOR k IN SELECT u.guard_key FROM admission_resource_uris u JOIN (SELECT DISTINCT uri FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) affected) a ON a.uri=u.uri ORDER BY u.guard_key COLLATE "C" LOOP
INSERT INTO admission_revisions(guard_key,revision) VALUES (k,1) ON CONFLICT(guard_key) DO UPDATE SET revision=admission_revisions.revision+1;
END LOOP;
INSERT INTO admission_stack_labels(label) SELECT DISTINCT label FROM (SELECT r.stack AS label FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Stack') FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Stack') FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r ON h.uri=r.uri) labels WHERE label IS NOT NULL ON CONFLICT(label) DO NOTHING;
FOR k IN SELECT guard_key FROM (SELECT l.guard_key FROM admission_stack_labels l JOIN (SELECT r.stack AS label FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Stack') FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Stack') FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r ON h.uri=r.uri) x ON l.label=x.label
UNION
SELECT CASE WHEN RTRIM(s.id) ~ '^[A-Za-z0-9_-]{1,128}$' THEN 'admission:stack:' || RTRIM(s.id) ELSE 'admission:stack:exceptional' END AS guard_key FROM stacks s JOIN (SELECT r.stack AS label FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r UNION SELECT (r.data::jsonb ->> 'Stack') FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r UNION SELECT h.stack FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r ON h.uri=r.uri UNION SELECT (h.data::jsonb ->> 'Stack') FROM resources h JOIN (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r ON h.uri=r.uri) x ON s.label=x.label
UNION
SELECT 'admission:topology' AS guard_key WHERE EXISTS (SELECT 1 FROM (SELECT OLD.stack AS stack, OLD.data AS data, OLD.uri AS uri, OLD.refs AS refs) r WHERE (CAST(r.data AS TEXT) LIKE '%$ref%' OR CAST(r.data AS TEXT) LIKE '%$gen%' OR CAST(r.data AS TEXT) LIKE '%' || chr(92) || '%') OR cardinality(r.refs)>0 OR EXISTS (SELECT 1 FROM resources h WHERE h.uri=r.uri AND ((CAST(h.data AS TEXT) LIKE '%$ref%' OR CAST(h.data AS TEXT) LIKE '%$gen%' OR CAST(h.data AS TEXT) LIKE '%' || chr(92) || '%') OR cardinality(h.refs)>0)))) keys ORDER BY guard_key COLLATE "C" LOOP
INSERT INTO admission_revisions(guard_key,revision) VALUES (k,1) ON CONFLICT(guard_key) DO UPDATE SET revision=admission_revisions.revision+1;
END LOOP;
RETURN OLD;
END $$;
-- +goose StatementEnd
DROP TABLE admission_resource_ids;
DROP TABLE admission_inventory_targets;
