name: formae-linter

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.1'

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8.0.0
      with:
        version: latest
        args: --config=.golangci.yml -v

  reuse-compliance:
    name: REUSE License Compliance
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v5